fix

diff --git a/_demo/project/vimrc-profile/vimrc-ctrl/vimrc-ctrl b/_demo/project/vimrc-profile/vimrc-ctrl/vimrc-ctrl
--- a/_demo/project/vimrc-profile/vimrc-ctrl/vimrc-ctrl
+++ b/_demo/project/vimrc-profile/vimrc-ctrl/vimrc-ctrl
@@ -327,7 +327,101 @@ is_not_vimrc_dir () {
 
 vimrc_find_dir_path_by_name () {
 	local name="$1"
-	echo "$THE_PROFILE_DIR_PATH/$name"
+	echo "$THE_VIMRC_PROFILE_DIR_PATH/$name"
+}
+
+
+
+vimrc_check_vimrc_dir_exists () {
+
+	local vimrc_dir_name=".vim"
+	local vimrc_dir_path="$HOME/$vimrc_dir_name"
+
+	if ! [ -a "$vimrc_dir_path" ]; then ## file not exists
+		return 0
+	fi
+
+
+	if [ -h "$vimrc_dir_path" ]; then ## ~/.vim is folder
+		return 0
+	fi
+
+
+
+	echo "Dir is exists:" "$vimrc_dir_path"
+	echo
+
+	echo "Try to backup:"
+	echo
+
+	local now=$(date +%Y%m%d_%s)
+	local bak_dir_path="${HOME}/.backup/vimrc.bak"
+	local bak_target_path="${bak_dir_path}/${vimrc_dir_name}.bak.${now}"
+
+	echo "mkdir -p ${bak_dir_path}"
+	mkdir -p "${bak_dir_path}"
+
+
+	echo "cp -a ${vimrc_dir_path} ${bak_target_path}"
+	cp -a "${vimrc_dir_path}" "${bak_target_path}"
+
+	if [ "$?" != "0" ]; then
+		echo
+		echo 'Backup Failure!'
+		#exit 1
+		return 1
+	fi
+
+	echo
+
+
+
+
+
+
+
+	return 0
+}
+
+
+vimrc_check_vimrc_file_exists () {
+
+	# :help vimrc
+
+	local vimrc_file_name=".vimrc"
+	local vimrc_file_path="$HOME/$vimrc_file_name"
+
+	if ! [ -a "$vimrc_file_path" ]; then ## file not exists
+		return 0
+	fi
+
+
+	echo "File is exists:" "$vimrc_file_path"
+	echo
+
+	echo "Try to backup:"
+	echo
+
+	local now=$(date +%Y%m%d_%s)
+	local bak_dir_path="${HOME}/.backup/vimrc.bak"
+	local bak_target_path="${bak_dir_path}/${vimrc_file_name}.bak.${now}"
+
+	echo "mkdir -p ${bak_dir_path}"
+	mkdir -p "${bak_dir_path}"
+
+	echo "mv ${vimrc_file_path} ${bak_target_path}"
+	mv "${vimrc_file_path}" "${bak_target_path}"
+
+	if [ "$?" != "0" ]; then
+		echo
+		echo 'Backup Failure!'
+		#exit 1
+		return 1
+	fi
+
+	echo
+
+	return 0
 }
 
 
@@ -342,7 +436,6 @@ vimrc_find_dir_path_by_name () {
 
 vimrc_profile_default () {
 	vimrc_profile_set 'default'
-
 }
 
 ##
@@ -413,6 +506,58 @@ vimrc_profile_get () {
 ##
 
 vimrc_profile_set () {
+	#echo "vimrc_profile_set"
+	#echo "$@"
+
+
+	## $ vimrc-ctrl set svim
+
+	local name="$1"
+	local source_dir_path="$THE_VIMRC_PROFILE_DIR_PATH/$name"
+	local target_dir_path="$THE_VIMRC_DIR_PATH"
+
+	#echo "target_dir_path=$target_dir_path"
+	#echo "source_dir_path=$source_dir_path"
+
+	if is_not_vimrc_dir "$source_dir_path"; then ## check ~/.vimrc-profile/demo/vimrc
+		echo "Not valid vimrc dir: $source_dir_path"
+		echo
+		echo 'Please run:'
+		echo '	$ vimrc-ctrl list'
+		echo 'to find valid vimrc dir.'
+		return 1
+	fi
+
+	vimrc_check_vimrc_dir_exists
+
+	vimrc_check_vimrc_file_exists
+
+
+	if [ -h "$target_dir_path" ]; then ## ~/.vim is symbolic link
+		echo
+		echo rm -f "$target_dir_path"
+		rm -f "$target_dir_path"
+	else
+		echo
+		echo rm -rf "$target_dir_path"
+		rm -rf "$target_dir_path"
+	fi
+
+
+
+
+	echo
+	echo ln -sf "$source_dir_path" "$target_dir_path"
+	ln -sf "$source_dir_path" "$target_dir_path"
+
+
+	echo
+	file "$target_dir_path"
+
+}
+
+
+vimrc_profile_set__prototype () {
 	#echo "vimrc_profile_set"
 	#echo "$@"
 
